Fix regression in restconfig caused by StyleController's catch-all ContentNegotiationStrategy
Override `PutIgnoringExtensionContentNegotiationStrategy` defined in
`StyleController$StyleControllerConfiguration` as it causes a
```
java.lang.IllegalArgumentException: Expected lookupPath in request attribute
org.springframework.web.util.UrlPathHelper.PATH".
```
exception for `/actuator/*` requests.