Manage webmvc transitive dependency from geoserver
Due to https://github.com/geoserver/geoserver/pull/4884,
excluding spring-webmvc from gs-main results in a
NoClassDefFoundError:
org/springframework/web/servlet/mvc/AbstractController. Before it was
coming as transitive of gs-ows anyways.

Yet webmvc can't be included in the reactive projects, so adding it in
provided scope where required.